name: maintix

services:
  server:
    build:
      context: ./server
    container_name: maintix-server-container
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - maintix-network

  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_API_URL=/api
    container_name: maintix-client-container
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - maintix-network

  nginx:
    image: nginx:alpine
    container_name: maintix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client
    networks:
      - maintix-network

networks:
  maintix-network:
    name: maintix-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
