export enum AuditAction {
  // Auth Actions
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  LOGOUT_CURRENT_SESSION = 'LOGOUT_CURRENT_SESSION',
  LOGOUT_SPECIFIC_SESSION = 'LOGOUT_SPECIFIC_SESSION',
  LOGOUT_ALL_SESSION = 'LOGOUT_ALL_SESSION',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',

  // Invitation Action
  SEND_INVITATION = 'SEND_INVITATION',
  ACCEPT_INVITATION = 'ACCEPT_INVITATION',

  // Organization Actions
  CREATE_ORG = 'CREATE_ORG',
  UPDATE_ORG = 'UPDATE_ORG',
  DEACTIVE_ORG = 'DEACTIVE_ORG',

  // Location Actions
  CREATE_LOCATION = 'CREATE_LOCATION',
  UPDATE_LOCATION = 'UPDATE_LOCATION',

  // Department Actions
  CREATE_DEPARTMENT = 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',

  //User Actions
  UPDATE_USER_NAME = 'UPDATE_USER_NAME',
  UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD',
  UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL',
  UPDATE_USER_ROLE = 'UPDATE_USER_ROLE',
  UPDATE_USER_DEPARTMENT = 'UPDATE_USER_DEPARTMENT',
  ACTIVATE_USER = 'ACTIVATE_USER',
  DEACTIVATE_USER = 'DEACTIVATE_USER',

  // Equipment type Actions
  CREATE_EQUIPMENT_TYPE = 'CREATE_EQUIPMENT_TYPE',
  UPDATE_EQUIPMENT_TYPE = 'UPDATE_EQUIPMENT_TYPE',
  DEACTIVATE_EQUIPMENT_TYPE = 'DEACTIVATE_EQUIPMENT_TYPE',
  ACTIVATE_EQUIPMENT_TYPE = 'ACTIVATE_EQUIPMENT_TYPE',

  // Equipment Actions
  CREATE_EQUIPMENT = 'CREATE_EQUIPMENT',
  UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT',
  DEACTIVATE_EQUIPMENT = 'DEACTIVATE_EQUIPMENT',
  ACTIVATE_EQUIPMENT = 'ACTIVATE_EQUIPMENT',

  // Checklist Actions
  CREATE_CHECKLIST = 'CREATE_CHECKLIST',
  UPDATE_CHECKLIST = 'UPDATE_CHECKLIST',
  DEACTIVATE_CHECKLIST = 'DEACTIVATE_CHECKLIST',

  // PMSchedule Actions
  CREATE_PMSCHEDULE = 'CREATE_PMSCHEDULE',
  UPDATE_PMSCHEDULE = 'UPDATE_PMSCHEDULE',
  DEACTIVATE_PMSCHEDULE = 'DEACTIVATE_PMSCHEDULE',
  ACTIVATE_PMSCHEDULE = 'ACTIVATE_PMSCHEDULE',

  // PMTask Actions
  UPDATE_PMTASK = 'UPDATE_PMTASK',
  COMPLETE_PMTASK = 'COMPLETE_PMTASK',

  // Breakdown Actions
  CREATE_BREAKDOWN = 'CREATE_BREAKDOWN',
  UPDATE_BREAKDOWN = 'UPDATE_BREAKDOWN',
}

export enum AuditModule {
  AUTH = 'AUTH',
  ORG = 'ORG',
  USER = 'USER',
  EQUIPMENT = 'EQUIPMENT',
  CHECKLIST = 'CHECKLIST',
  PM = 'PM',
  BREAKDOWN = 'BREAKDOWN',
}

export type AuditParamsType = {
  organizationId: number;
  userId: number;
  action: AuditAction;
  module: AuditModule;
  recordId: string;
  ipAddress?: string;
};
