name: Maintix CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  client:
    name: Client CI
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build client
        run: npm run build

  server:
    name: Server CI
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      PORT: ${{secrets.PORT}}
      JWT_ACCESS_SECRET: ${{secrets.CI_JWT_ACCESS_SECRET}}
      JWT_REFRESH_SECRET: ${{secrets.CI_JWT_REFRESH_SECRET}}
      EMAIL_ID: ${{secrets.EMAIL_ID}}
      EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
      EMAIL_HOST: ${{secrets.EMAIL_HOST}}
      EMAIL_PORT: ${{secrets.EMAIL_PORT}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
      CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
      CLIENT_URL: ${{secrets.CLIENT_URL}}

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: maintix_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d maintix_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      - name: Seed test database
        run: npx prisma db seed

      - name: Run login E2E test
        run: npm run test:e2e -- test/e2e/auth/login.e2e-spec.ts

      - name: Build server
        run: npm run build
